# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qspatialite.ui'
#
# Created: Wed Jun 01 14:31:35 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QspatiaLite(object):
    def setupUi(self, QspatiaLite):
        QspatiaLite.setObjectName(_fromUtf8("QspatiaLite"))
        QspatiaLite.resize(790, 625)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QspatiaLite.sizePolicy().hasHeightForWidth())
        QspatiaLite.setSizePolicy(sizePolicy)
        self.verticalLayout_7 = QtGui.QVBoxLayout(QspatiaLite)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.newdb = QtGui.QPushButton(QspatiaLite)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newdb.sizePolicy().hasHeightForWidth())
        self.newdb.setSizePolicy(sizePolicy)
        self.newdb.setMaximumSize(QtCore.QSize(75, 16777215))
        self.newdb.setObjectName(_fromUtf8("newdb"))
        self.horizontalLayout_7.addWidget(self.newdb)
        self.connexionDB = QtGui.QComboBox(QspatiaLite)
        self.connexionDB.setObjectName(_fromUtf8("connexionDB"))
        self.horizontalLayout_7.addWidget(self.connexionDB)
        self.vacuum = QtGui.QPushButton(QspatiaLite)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vacuum.sizePolicy().hasHeightForWidth())
        self.vacuum.setSizePolicy(sizePolicy)
        self.vacuum.setMaximumSize(QtCore.QSize(100, 35))
        self.vacuum.setObjectName(_fromUtf8("vacuum"))
        self.horizontalLayout_7.addWidget(self.vacuum)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.splitter = QtGui.QSplitter(QspatiaLite)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeView = QtGui.QTreeView(self.splitter)
        self.treeView.setMinimumSize(QtCore.QSize(0, 0))
        self.treeView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setIconSize(QtCore.QSize(12, 12))
        self.treeView.setExpandsOnDoubleClick(False)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.splitter_2 = QtGui.QSplitter(self.tab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.toolButton = QtGui.QToolButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(8)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.helpsql = QtGui.QToolButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(8)
        self.helpsql.setFont(font)
        self.helpsql.setObjectName(_fromUtf8("helpsql"))
        self.horizontalLayout_4.addWidget(self.helpsql)
        self.precedent = QtGui.QToolButton(self.layoutWidget)
        self.precedent.setObjectName(_fromUtf8("precedent"))
        self.horizontalLayout_4.addWidget(self.precedent)
        self.suivant = QtGui.QToolButton(self.layoutWidget)
        self.suivant.setObjectName(_fromUtf8("suivant"))
        self.horizontalLayout_4.addWidget(self.suivant)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        #self.SQLeditor = QtGui.QTextEdit(self.layoutWidget)
	#new one
	import autocompletion
	completer = autocompletion.DictionaryCompleter()
	self.SQLeditor = autocompletion.CompletionTextEdit(self.layoutWidget)
	self.SQLeditor.setCompleter(completer)
	self.SQLeditor.setAcceptRichText(False)
	#---------
        self.SQLeditor.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        self.SQLeditor.setFont(font)
        self.SQLeditor.setObjectName(_fromUtf8("SQLeditor"))
        self.verticalLayout_2.addWidget(self.SQLeditor)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(147, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.Command = QtGui.QComboBox(self.layoutWidget1)
        self.Command.setMinimumSize(QtCore.QSize(150, 0))
        self.Command.setObjectName(_fromUtf8("Command"))
        self.verticalLayout_3.addWidget(self.Command)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.tablename = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tablename.setFont(font)
        self.tablename.setObjectName(_fromUtf8("tablename"))
        self.verticalLayout_3.addWidget(self.tablename)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.geometry = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.geometry.setFont(font)
        self.geometry.setObjectName(_fromUtf8("geometry"))
        self.verticalLayout_3.addWidget(self.geometry)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.id = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.id.setFont(font)
        self.id.setObjectName(_fromUtf8("id"))
        self.verticalLayout_3.addWidget(self.id)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addWidget(self.splitter_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.Result = QtGui.QLabel(self.tab)
        self.Result.setObjectName(_fromUtf8("Result"))
        self.horizontalLayout_9.addWidget(self.Result)
        spacerItem1 = QtGui.QSpacerItem(268, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.time = QtGui.QLabel(self.tab)
        self.time.setObjectName(_fromUtf8("time"))
        self.horizontalLayout_9.addWidget(self.time)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.result = QtGui.QTableView(self.tab)
        self.result.setMinimumSize(QtCore.QSize(0, 0))
        self.result.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.result.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.result.setObjectName(_fromUtf8("result"))
        self.verticalLayout_5.addWidget(self.result)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem2 = QtGui.QSpacerItem(137, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem3)
        self.label_8 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_18.addWidget(self.label_8)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem4 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.layerlist = QtGui.QComboBox(self.tab_4)
        self.layerlist.setObjectName(_fromUtf8("layerlist"))
        self.verticalLayout.addWidget(self.layerlist)
        self.verticalLayout_18.addLayout(self.verticalLayout)
        self.selectedvalues = QtGui.QCheckBox(self.tab_4)
        self.selectedvalues.setObjectName(_fromUtf8("selectedvalues"))
        self.verticalLayout_18.addWidget(self.selectedvalues)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.name = QtGui.QLineEdit(self.tab_4)
        self.name.setObjectName(_fromUtf8("name"))
        self.verticalLayout_15.addWidget(self.name)
        self.verticalLayout_18.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_14.addWidget(self.label_12)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.srid = QtGui.QLineEdit(self.tab_4)
        self.srid.setObjectName(_fromUtf8("srid"))
        self.horizontalLayout_3.addWidget(self.srid)
        self.searchSRID = QtGui.QToolButton(self.tab_4)
        self.searchSRID.setObjectName(_fromUtf8("searchSRID"))
        self.horizontalLayout_3.addWidget(self.searchSRID)
        self.verticalLayout_16.addLayout(self.horizontalLayout_3)
        self.verticalLayout_18.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.verticalLayout_17.addLayout(self.horizontalLayout_16)
        self.charsetList = QtGui.QComboBox(self.tab_4)
        self.charsetList.setObjectName(_fromUtf8("charsetList"))
        self.verticalLayout_17.addWidget(self.charsetList)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.SpatialIndex = QtGui.QCheckBox(self.tab_4)
        self.SpatialIndex.setObjectName(_fromUtf8("SpatialIndex"))
        self.verticalLayout_18.addWidget(self.SpatialIndex)
        self.virtualShape = QtGui.QCheckBox(self.tab_4)
        self.virtualShape.setObjectName(_fromUtf8("virtualShape"))
        self.verticalLayout_18.addWidget(self.virtualShape)
        self.uploadQGIS = QtGui.QPushButton(self.tab_4)
        self.uploadQGIS.setObjectName(_fromUtf8("uploadQGIS"))
        self.verticalLayout_18.addWidget(self.uploadQGIS)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem8)
        self.horizontalLayout_17.addLayout(self.verticalLayout_18)
        spacerItem9 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem10 = QtGui.QSpacerItem(142, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem11)
        self.label_19 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_19.addWidget(self.label_19)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_20 = QtGui.QLabel(self.tab_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_11.addWidget(self.label_20)
        spacerItem12 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.charsetList_DBF = QtGui.QComboBox(self.tab_5)
        self.charsetList_DBF.setObjectName(_fromUtf8("charsetList_DBF"))
        self.verticalLayout_4.addWidget(self.charsetList_DBF)
        self.verticalLayout_19.addLayout(self.verticalLayout_4)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_18 = QtGui.QLabel(self.tab_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_13.addWidget(self.label_18)
        spacerItem13 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dbf_path = QtGui.QLineEdit(self.tab_5)
        self.dbf_path.setObjectName(_fromUtf8("dbf_path"))
        self.horizontalLayout.addWidget(self.dbf_path)
        self.searchDBF = QtGui.QToolButton(self.tab_5)
        self.searchDBF.setObjectName(_fromUtf8("searchDBF"))
        self.horizontalLayout.addWidget(self.searchDBF)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.verticalLayout_19.addLayout(self.verticalLayout_10)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem14 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.name_dbf = QtGui.QLineEdit(self.tab_5)
        self.name_dbf.setObjectName(_fromUtf8("name_dbf"))
        self.verticalLayout_14.addWidget(self.name_dbf)
        self.verticalLayout_19.addLayout(self.verticalLayout_14)
        self.uploadDBF = QtGui.QPushButton(self.tab_5)
        self.uploadDBF.setObjectName(_fromUtf8("uploadDBF"))
        self.verticalLayout_19.addWidget(self.uploadDBF)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem15)
        self.horizontalLayout_18.addLayout(self.verticalLayout_19)
        spacerItem16 = QtGui.QSpacerItem(142, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem16)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        spacerItem17 = QtGui.QSpacerItem(66, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem17)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        spacerItem18 = QtGui.QSpacerItem(272, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem18)
        self.label_21 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_25.addWidget(self.label_21)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_20.addWidget(self.label_23)
        spacerItem19 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.csv_path = QtGui.QLineEdit(self.tab_2)
        self.csv_path.setObjectName(_fromUtf8("csv_path"))
        self.horizontalLayout_5.addWidget(self.csv_path)
        self.searchCSV = QtGui.QToolButton(self.tab_2)
        self.searchCSV.setObjectName(_fromUtf8("searchCSV"))
        self.horizontalLayout_5.addWidget(self.searchCSV)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem20)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.verticalLayout_25.addLayout(self.verticalLayout_11)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_21.addWidget(self.label_16)
        spacerItem21 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem21)
        self.verticalLayout_21.addLayout(self.horizontalLayout_21)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.name_csv = QtGui.QLineEdit(self.tab_2)
        self.name_csv.setObjectName(_fromUtf8("name_csv"))
        self.horizontalLayout_28.addWidget(self.name_csv)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem22)
        self.verticalLayout_22.addLayout(self.horizontalLayout_28)
        self.verticalLayout_25.addLayout(self.verticalLayout_22)
        self.first_col = QtGui.QCheckBox(self.tab_2)
        self.first_col.setObjectName(_fromUtf8("first_col"))
        self.verticalLayout_25.addWidget(self.first_col)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_19.addWidget(self.label_22)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem23)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.charsetList_CSV = QtGui.QComboBox(self.tab_2)
        self.charsetList_CSV.setObjectName(_fromUtf8("charsetList_CSV"))
        self.verticalLayout_6.addWidget(self.charsetList_CSV)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_26 = QtGui.QLabel(self.tab_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_22.addWidget(self.label_26)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem24)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.decimal = QtGui.QComboBox(self.tab_2)
        self.decimal.setObjectName(_fromUtf8("decimal"))
        self.verticalLayout_9.addWidget(self.decimal)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 1, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_27 = QtGui.QLabel(self.tab_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_25.addWidget(self.label_27)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem25)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.text = QtGui.QComboBox(self.tab_2)
        self.text.setObjectName(_fromUtf8("text"))
        self.verticalLayout_12.addWidget(self.text)
        self.gridLayout.addLayout(self.verticalLayout_12, 1, 0, 1, 1)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_28 = QtGui.QLabel(self.tab_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_26.addWidget(self.label_28)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem26)
        self.verticalLayout_20.addLayout(self.horizontalLayout_26)
        self.column = QtGui.QComboBox(self.tab_2)
        self.column.setObjectName(_fromUtf8("column"))
        self.verticalLayout_20.addWidget(self.column)
        self.gridLayout.addLayout(self.verticalLayout_20, 1, 1, 1, 1)
        self.verticalLayout_25.addLayout(self.gridLayout)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem27)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_27.addWidget(self.label)
        self.custom_col = QtGui.QLineEdit(self.tab_2)
        self.custom_col.setMaximumSize(QtCore.QSize(100, 16777215))
        self.custom_col.setObjectName(_fromUtf8("custom_col"))
        self.horizontalLayout_27.addWidget(self.custom_col)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem28)
        self.verticalLayout_25.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem29)
        self.uploadCSV = QtGui.QPushButton(self.tab_2)
        self.uploadCSV.setObjectName(_fromUtf8("uploadCSV"))
        self.horizontalLayout_31.addWidget(self.uploadCSV)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem30)
        self.verticalLayout_25.addLayout(self.horizontalLayout_31)
        spacerItem31 = QtGui.QSpacerItem(272, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem31)
        self.horizontalLayout_29.addLayout(self.verticalLayout_25)
        spacerItem32 = QtGui.QSpacerItem(66, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem32)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_13.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.splitter)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem33)
        self.label_3 = QtGui.QLabel(QspatiaLite)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.SpatiaLiteVersion = QtGui.QLabel(QspatiaLite)
        self.SpatiaLiteVersion.setMaximumSize(QtCore.QSize(16777215, 20))
        self.SpatiaLiteVersion.setObjectName(_fromUtf8("SpatiaLiteVersion"))
        self.horizontalLayout_8.addWidget(self.SpatiaLiteVersion)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.helpquit = QtGui.QDialogButtonBox(QspatiaLite)
        self.helpquit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.helpquit.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.helpquit.setObjectName(_fromUtf8("helpquit"))
        self.verticalLayout_7.addWidget(self.helpquit)

        self.retranslateUi(QspatiaLite)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.helpquit, QtCore.SIGNAL(_fromUtf8("rejected()")), QspatiaLite.reject)
        QtCore.QMetaObject.connectSlotsByName(QspatiaLite)

    def retranslateUi(self, QspatiaLite):
        QspatiaLite.setWindowTitle(QtGui.QApplication.translate("QspatiaLite", "QspatiaLite", None, QtGui.QApplication.UnicodeUTF8))
        self.newdb.setToolTip(QtGui.QApplication.translate("QspatiaLite", "Create a new Spatial DataBase\n"
"(you can also load an existing one, just ignore \"replace\" message!)", None, QtGui.QApplication.UnicodeUTF8))
        self.newdb.setText(QtGui.QApplication.translate("QspatiaLite", "New DB", None, QtGui.QApplication.UnicodeUTF8))
        self.connexionDB.setToolTip(QtGui.QApplication.translate("QspatiaLite", "Select current Database Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuum.setToolTip(QtGui.QApplication.translate("QspatiaLite", "VACUUM current database", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuum.setText(QtGui.QApplication.translate("QspatiaLite", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("QspatiaLite", "Use CTRL+E to Trigger AutoCompletion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("QspatiaLite", "SQL editor", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("QspatiaLite", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier 10 Pitch\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Create SQl Query easily</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("QspatiaLite", "Query Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.helpsql.setToolTip(QtGui.QApplication.translate("QspatiaLite", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier 10 Pitch\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Show SpatiaLite Documentation (v2.4)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.helpsql.setText(QtGui.QApplication.translate("QspatiaLite", "Functions list", None, QtGui.QApplication.UnicodeUTF8))
        self.precedent.setToolTip(QtGui.QApplication.translate("QspatiaLite", "Previous query", None, QtGui.QApplication.UnicodeUTF8))
        self.precedent.setText(QtGui.QApplication.translate("QspatiaLite", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.suivant.setToolTip(QtGui.QApplication.translate("QspatiaLite", "Next query", None, QtGui.QApplication.UnicodeUTF8))
        self.suivant.setText(QtGui.QApplication.translate("QspatiaLite", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.SQLeditor.setHtml(QtGui.QApplication.translate("QspatiaLite", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier 10 Pitch\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans MS\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("QspatiaLite", "Table name", None, QtGui.QApplication.UnicodeUTF8))
        self.tablename.setToolTip(QtGui.QApplication.translate("QspatiaLite", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter desired New Table/View/Layer Name</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("QspatiaLite", "Geometry column", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setToolTip(QtGui.QApplication.translate("QspatiaLite", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter corresponding geometry column name</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("QspatiaLite", "Id column", None, QtGui.QApplication.UnicodeUTF8))
        self.id.setToolTip(QtGui.QApplication.translate("QspatiaLite", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Primary keys, or ROWID in other cases</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("QspatiaLite", "Run SQL Query", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("QspatiaLite", "Run Query", None, QtGui.QApplication.UnicodeUTF8))
        self.Result.setText(QtGui.QApplication.translate("QspatiaLite", "ResultSet", None, QtGui.QApplication.UnicodeUTF8))
        self.time.setText(QtGui.QApplication.translate("QspatiaLite", "Elapsed Time: ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("QspatiaLite", "SQL Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("QspatiaLite", "Import QGIS Layer ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("QspatiaLite", "QGIS Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.selectedvalues.setToolTip(QtGui.QApplication.translate("QspatiaLite", "Upload only selected values from QGIS map canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.selectedvalues.setText(QtGui.QApplication.translate("QspatiaLite", "Only Selected Values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("QspatiaLite", "New Table Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("QspatiaLite", "SRID", None, QtGui.QApplication.UnicodeUTF8))
        self.searchSRID.setText(QtGui.QApplication.translate("QspatiaLite", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("QspatiaLite", "Charset", None, QtGui.QApplication.UnicodeUTF8))
        self.charsetList.setToolTip(QtGui.QApplication.translate("QspatiaLite", "Choose charset for imported table \n"
"( can be different from QGIS Layer original\'s Charset)", None, QtGui.QApplication.UnicodeUTF8))
        self.SpatialIndex.setText(QtGui.QApplication.translate("QspatiaLite", "Create Spatial Index", None, QtGui.QApplication.UnicodeUTF8))
        self.virtualShape.setText(QtGui.QApplication.translate("QspatiaLite", "Use VirtualShape Import", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadQGIS.setText(QtGui.QApplication.translate("QspatiaLite", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("QspatiaLite", "QGIS Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("QspatiaLite", "Import DBF Table", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("QspatiaLite", "DBF Charset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("QspatiaLite", "DBF File", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDBF.setText(QtGui.QApplication.translate("QspatiaLite", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("QspatiaLite", "New Table Name", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadDBF.setText(QtGui.QApplication.translate("QspatiaLite", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("QspatiaLite", "DBF File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("QspatiaLite", "Import CSV/TXT File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("QspatiaLite", "File Path", None, QtGui.QApplication.UnicodeUTF8))
        self.searchCSV.setText(QtGui.QApplication.translate("QspatiaLite", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("QspatiaLite", "New Table Name", None, QtGui.QApplication.UnicodeUTF8))
        self.first_col.setText(QtGui.QApplication.translate("QspatiaLite", "Columns names in first line ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("QspatiaLite", "File Charset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("QspatiaLite", "Decimal separator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("QspatiaLite", "Text Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("QspatiaLite", "Column Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("QspatiaLite", "Custom Column Separator:", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadCSV.setText(QtGui.QApplication.translate("QspatiaLite", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QtGui.QApplication.translate("QspatiaLite", "CSV-TXT", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("QspatiaLite", "Upload Tables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("QspatiaLite", "SpatiaLite version", None, QtGui.QApplication.UnicodeUTF8))
        self.SpatiaLiteVersion.setText(QtGui.QApplication.translate("QspatiaLite", "Version", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    QspatiaLite = QtGui.QDialog()
    ui = Ui_QspatiaLite()
    ui.setupUi(QspatiaLite)
    QspatiaLite.show()
    sys.exit(app.exec_())

